data_whole <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, colClasses=c(Date = "character", Time = "character", rep("numeric",7)), na.strings = "?")
data_whole$Date <- as.Date(data_whole$Date, "%d/%m/%Y")
data_whole$Time <- strptime(data_whole$Time, "%H:%M:%S")
data_power <- subset(data_whole, data_whole$Date == c("2007-02-01", "2007-02-02"))
data_plot <- data.frame(Time = strptime(paste(data_power$Date,data_power$Time, sep=" "), format = "%Y-%m-%d %H:%M:%S"), Gobal_active_power = data_power$Global_active_power, Gobal_reactive_power = data_power$Global_reactive_power, Voltage = data_power$Voltage, Sub_metering_1 = data_power$Sub_metering_1, Sub_metering_2 = data_power$Sub_metering_2, Sub_metering_3 = data_power$Sub_metering_3)
par(mfcol = c(2,2))
plot(data_plot$Time, data_plot$Gobal_active_power,type="n",ylab="Global Active Power (kilowatts)", xlab = "")
lines(data_plot$Time, data_plot$Gobal_active_power)
plot(data_plot$Time, data_plot$Sub_metering_1,type="n",ylab="Energy sub metering", xlab = "")
lines(data_plot$Time, data_plot$Sub_metering_1)
lines(data_plot$Time, data_plot$Sub_metering_2, col = "red")
lines(data_plot$Time, data_plot$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lwd = c(2.5,2.5,2.5), col = c("black","red","blue"))
plot(data_plot$Time, data_plot$Voltage,type="n",ylab="Voltage", xlab = "datetime")
lines(data_plot$Time, data_plot$Voltage)
plot(data_plot$Time, data_plot$Gobal_reactive_power,type="n",ylab="Global_reactive_power", xlab = "datetime")
lines(data_plot$Time, data_plot$Gobal_reactive_power)
dev.copy(png, file = "plot4.png")
dev.off()
